/*
 * This source file was generated by the Gradle 'init' task
 */
package io.anirudhchhangani;

public class FibonacciNaive {

    public long fib(long n) {
        if (n <= 1) {
            return n;
        }
        return fib(n - 1) + fib(n - 2);
    }

    static void main(String[] args) {
        System.out.println(new FibonacciNaive().fib(10));
    }
}
