/*
 * This source file was generated by the Gradle 'init' task
 */
package io.anirudhchhangani;

import org.junit.Test;
import static org.junit.Assert.*;

public class FibonacciNaiveTest {
    @Test public void appHasAFib() {
        FibonacciNaive classUnderTest = new FibonacciNaive();
        assert classUnderTest.fib(10) == 55;
    }
}
