/*
 * This source file was generated by the Gradle 'init' task
 */
package io.anirudhchhangani;

import org.junit.Test;

public class LongestSubstringWithoutDuplicatesTest {
    @Test public void solutionTest() {
        LongestSubstringWithoutDuplicates classUnderTest = new LongestSubstringWithoutDuplicates();
        String s = "abcabcbbksahiajknmvhfipsaknflaaafnfbajrfiejfbka";
        int result = classUnderTest.lengthOfLongestSubstring(s);
        assert result == 11;
    }
}
